# this file is *not* meant to cover or endorse the use of GitHub Actions, but rather to
# help test this project

name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10']
        platform: [ubuntu-latest] #, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install ta-lib
      run: |
        if ([ "$RUNNER_OS" = "macOS" ]); then
          brew install ta-lib
        fi
        if ([ "$RUNNER_OS" = "Linux" ]); then
          if [ ! -f "$GITHUB_WORKSPACE/ta-lib/src" ]; then wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz -q && tar -xzf ta-lib-0.4.0-src.tar.gz; fi
          cd ta-lib/
          ./configure --prefix=/usr
          if [ ! -f "$HOME/ta-lib/src" ]; then make; fi
          sudo make install
          cd
        fi
        if ([ "$RUNNER_OS" = "Windows" ]); then
          curl -sL http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-msvc.zip -o $GITHUB_WORKSPACE/ta-lib.zip --create-dirs && 7z x $GITHUB_WORKSPACE/ta-lib.zip -o/c/ta-lib && mv /c/ta-lib/ta-lib/* /c/ta-lib/ && rm -rf /c/ta-lib/ta-lib && cd /c/ta-lib/c/make/cdr/win32/msvc && nmake
        fi        
    - name: Install test dependencies
      run: python -m pip install -U tox
    - name: Test
      run: python -m tox -e py
